# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-29 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ip_addr', models.IntegerField()),
                ('ipmi_addr', models.IntegerField()),
                ('password', models.CharField(max_length=64)),
            ],
        ),
    ]
