# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-01 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostinfo', '0002_auto_20170929_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostinfo',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
