# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-01 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostinfo', '0004_auto_20171001_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostinfo',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
